const PDFDocument = require("pdfkit");
const { APP_NAME } = require("./brand");

const PLATFORM_NAME = "ExpenseOrbit Platform";

const COLOR = {
  primary:      "#5B4FE5",
  primarySoft:  "#EEEBFB",
  text:         "#0F172A",
  subtle:       "#334155",
  muted:        "#64748B",
  border:       "#E2E8F0",
  borderSoft:   "#EEF2F7",
  white:        "#FFFFFF",

  paid:         "#16A34A",
  paidSoft:     "#E7F7EC",
  pending:      "#B45309",
  pendingSoft:  "#FEF3E2",
  overdue:      "#DC2626",
  overdueSoft:  "#FDECEC"
};

const MONTH_NAMES = ["January","February","March","April","May","June","July","August","September","October","November","December"];

function formatRs(amount) {
  const n = Number(amount || 0);
  return "Rs." + n.toLocaleString("en-IN", { maximumFractionDigits: 0 });
}
function formatISODate(d) {
  const date = d instanceof Date ? d : new Date(d);
  if (Number.isNaN(date.getTime())) return "—";
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${dd}`;
}
function formatLongDate(d) {
  const date = d instanceof Date ? d : new Date(d);
  return `${date.getDate()} ${MONTH_NAMES[date.getMonth()]} ${date.getFullYear()}`;
}
function formatShortDate(d) {
  const date = d instanceof Date ? d : new Date(d);
  return `${date.getDate()}/${date.getMonth() + 1}/${date.getFullYear()}`;
}
function agreementId(date) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const suffix = String(Math.floor(10000 + Math.random() * 90000));
  return `SLA-${y}${m}${d}-${suffix}`;
}
function periodLabel(date) {
  return `${MONTH_NAMES[date.getMonth()]} ${date.getFullYear()}`;
}

function summarize(expenses) {
  let total = 0, paid = 0, pending = 0, overdue = 0;
  for (const e of expenses) {
    const amt = Number(e.amount) || 0;
    total += amt;
    if (e.status === "paid") paid += amt;
    else if (e.status === "overdue") overdue += amt;
    else pending += amt;
  }
  return { total, paid, pending, overdue };
}

function drawTopBar(doc) {
  const w = doc.page.width;
  doc.save();
  doc.rect(0, 0, w, 34).fill(COLOR.primary);
  doc.fillColor(COLOR.white).font("Helvetica-Bold").fontSize(10);
  doc.text("EXPENSEORBIT PLATFORM", 40, 12, { characterSpacing: 1 });
  doc.text("CONFIDENTIAL DOCUMENT", 0, 12, { width: w - 40, align: "right", characterSpacing: 1 });
  doc.restore();
}

function drawFooter(doc, meta, pageNum, totalPages) {
  const y = doc.page.height - 50;
  const w = doc.page.width;
  const savedBottom = doc.page.margins.bottom;
  doc.page.margins.bottom = 0;

  doc.save();
  doc.strokeColor(COLOR.border).lineWidth(0.5).moveTo(40, y).lineTo(w - 40, y).stroke();
  doc.fillColor(COLOR.muted).font("Helvetica").fontSize(8);
  const leftText = `Generated by ${PLATFORM_NAME} | ${meta.agreementNo} | ${formatShortDate(meta.generatedAt)} | Confidential`;
  doc.text(leftText, 40, y + 16, { width: w - 200, align: "center", lineBreak: false });
  doc.text(`Page ${pageNum} of ${totalPages}`, w - 140, y + 16, { width: 100, align: "right", lineBreak: false });
  doc.restore();

  doc.page.margins.bottom = savedBottom;
}

function drawHeader(doc, meta) {
  const xLeft = 40;
  const xRight = doc.page.width - 40;
  const topY = 62;

  doc.fillColor(COLOR.text).font("Helvetica-Bold").fontSize(26);
  doc.text(meta.companyName, xLeft, topY, { width: 340 });

  doc.fillColor(COLOR.subtle).font("Helvetica").fontSize(11);
  doc.text("Service Level Agreement — Expense Report", xLeft, topY + 36, { width: 340 });

  const rightTop = topY + 2;
  doc.fillColor(COLOR.subtle).font("Helvetica").fontSize(9);
  doc.text(`Agreement No: ${meta.agreementNo}`, 360, rightTop,       { width: xRight - 360, align: "right" });
  doc.text(`Generated: ${formatLongDate(meta.generatedAt)}`, 360, rightTop + 14, { width: xRight - 360, align: "right" });
  doc.text(`Period: ${meta.period}`, 360, rightTop + 28,             { width: xRight - 360, align: "right" });
  doc.fillColor(COLOR.text).font("Helvetica-Bold").fontSize(9);
  doc.text(`Status: ${meta.status}`, 360, rightTop + 44,             { width: xRight - 360, align: "right" });

  const ruleY = topY + 72;
  doc.save();
  doc.strokeColor(COLOR.primary).lineWidth(1.5).moveTo(xLeft, ruleY).lineTo(xRight, ruleY).stroke();
  doc.restore();

  const preambleY = ruleY + 14;
  doc.fillColor(COLOR.subtle).font("Helvetica").fontSize(9);
  const preamble = "This Service Level Agreement is entered into as of the date set forth above between the named entity (Client) and ExpenseOrbit Platform (Service Provider). This document constitutes an official record of all tracked expenditures and their associated terms. All amounts are expressed in Indian Rupees (INR).";
  doc.text(preamble, xLeft, preambleY, { width: xRight - xLeft, lineGap: 1.5 });

  doc.y = preambleY + doc.heightOfString(preamble, { width: xRight - xLeft, lineGap: 1.5 }) + 18;
}

function drawKpis(doc, summary) {
  const xLeft = 40;
  const xRight = doc.page.width - 40;
  const gap = 10;
  const width = (xRight - xLeft - gap * 3) / 4;
  const y = doc.y;
  const h = 64;

  const cards = [
    { label: "TOTAL EXPENSES", value: formatRs(summary.total),   stroke: COLOR.primary, fill: COLOR.primarySoft, value_color: COLOR.primary },
    { label: "PAID",           value: formatRs(summary.paid),    stroke: COLOR.paid,    fill: COLOR.paidSoft,    value_color: COLOR.paid },
    { label: "PENDING",        value: formatRs(summary.pending), stroke: COLOR.pending, fill: COLOR.pendingSoft, value_color: COLOR.pending },
    { label: "OVERDUE",        value: formatRs(summary.overdue), stroke: COLOR.overdue, fill: COLOR.overdueSoft, value_color: COLOR.overdue }
  ];

  cards.forEach((c, i) => {
    const x = xLeft + i * (width + gap);
    doc.save();
    doc.roundedRect(x, y, width, h, 8).fillAndStroke(c.fill, c.stroke);
    doc.fillColor(COLOR.muted).font("Helvetica-Bold").fontSize(8);
    doc.text(c.label, x, y + 14, { width, align: "center", characterSpacing: 1 });
    doc.fillColor(c.value_color).font("Helvetica-Bold").fontSize(14);
    doc.text(c.value, x, y + 34, { width, align: "center" });
    doc.restore();
  });

  doc.y = y + h + 24;
}

function drawSectionTitle(doc, text) {
  doc.fillColor(COLOR.primary).font("Helvetica-Bold").fontSize(11);
  doc.text(text, 40, doc.y, { characterSpacing: 0.5 });
  doc.moveDown(0.6);
}

function drawLedgerTable(doc, expenses, summary) {
  const xLeft = 40;
  const xRight = doc.page.width - 40;
  const fullW = xRight - xLeft;
  const cols = [
    { key: "i",    title: "#",             w: 0.05, align: "center" },
    { key: "name", title: "Expense Name",  w: 0.24, align: "left" },
    { key: "cat",  title: "Category",      w: 0.13, align: "center" },
    { key: "type", title: "Type",          w: 0.10, align: "center" },
    { key: "freq", title: "Frequency",     w: 0.10, align: "center" },
    { key: "date", title: "Date",          w: 0.12, align: "center" },
    { key: "amt",  title: "Amount",        w: 0.14, align: "right" },
    { key: "st",   title: "Status",        w: 0.12, align: "center" }
  ];
  const widths = cols.map((c) => c.w * fullW);
  const xs = [];
  { let acc = xLeft; for (const w of widths) { xs.push(acc); acc += w; } }

  const headerH = 28;
  let y = doc.y;

  doc.save();
  doc.rect(xLeft, y, fullW, headerH).fill(COLOR.primary);
  doc.fillColor(COLOR.white).font("Helvetica-Bold").fontSize(8.5);
  cols.forEach((c, i) => {
    doc.text(c.title.toUpperCase(), xs[i] + 4, y + 10, { width: widths[i] - 8, align: c.align, characterSpacing: 0.5 });
  });
  doc.restore();
  y += headerH;

  const typeLabel = (t) => t === "one-time" ? "one time" : (t || "");
  const statusColor = (s) => s === "paid" ? COLOR.paid : s === "overdue" ? COLOR.overdue : COLOR.pending;

  expenses.forEach((e, idx) => {
    const values = [
      String(idx + 1),
      e.name || "",
      e.category || "Other",
      typeLabel(e.type),
      e.recurringType || "—",
      formatISODate(e.type === "recurring" ? e.nextDueDate || e.date : e.date),
      formatRs(e.amount),
      String(e.status || "pending").toUpperCase()
    ];
    const rowH = 36;

    if (y + rowH > doc.page.height - 80) {
      doc.addPage();
      y = 80;
    }

    doc.save();
    doc.strokeColor(COLOR.border).lineWidth(0.5);
    doc.rect(xLeft, y, fullW, rowH).stroke();
    for (let i = 1; i < cols.length; i++) {
      doc.moveTo(xs[i], y).lineTo(xs[i], y + rowH).stroke();
    }
    doc.restore();

    cols.forEach((c, i) => {
      const cellX = xs[i] + 4;
      const cellW = widths[i] - 8;
      const val = values[i];
      const isStatus = c.key === "st";
      const isAmt = c.key === "amt";
      const isIdx = c.key === "i";

      if (isStatus) {
        doc.fillColor(statusColor(e.status)).font("Helvetica-Bold").fontSize(9);
      } else if (isAmt) {
        doc.fillColor(COLOR.text).font("Helvetica-Bold").fontSize(9.5);
      } else if (isIdx) {
        doc.fillColor(COLOR.muted).font("Helvetica").fontSize(9);
      } else {
        doc.fillColor(COLOR.subtle).font("Helvetica").fontSize(9);
      }
      const textH = doc.heightOfString(val, { width: cellW, align: c.align });
      const textY = y + (rowH - textH) / 2;
      doc.text(val, cellX, textY, { width: cellW, align: c.align });
    });

    y += rowH;
  });

  if (y + 32 > doc.page.height - 80) { doc.addPage(); y = 80; }
  const totalH = 32;
  doc.save();
  doc.strokeColor(COLOR.border).lineWidth(0.5);
  doc.rect(xLeft, y, fullW, totalH).stroke();
  for (let i = 1; i < cols.length; i++) {
    doc.moveTo(xs[i], y).lineTo(xs[i], y + totalH).stroke();
  }
  doc.restore();

  doc.fillColor(COLOR.primary).font("Helvetica-Bold").fontSize(10);
  doc.text("TOTAL", xs[1] + 4, y + (totalH - 12) / 2, { width: widths[1] - 8, align: "left" });
  doc.fillColor(COLOR.text).fontSize(10);
  doc.text(formatRs(summary.total), xs[6] + 4, y + (totalH - 12) / 2, { width: widths[6] - 8, align: "right" });
  doc.fillColor(COLOR.primary).fontSize(9);
  doc.text(`${expenses.length} items`, xs[7] + 4, y + (totalH - 12) / 2, { width: widths[7] - 8, align: "center" });

  doc.y = y + totalH + 24;
}

function drawTerms(doc) {
  drawSectionTitle(doc, "TERMS AND CONDITIONS");
  const items = [
    "All expenses listed herein are subject to review and approval by the authorised financial officer.",
    "Recurring expenses are automatically tracked and will appear in subsequent monthly reports.",
    "Overdue payments must be settled within 15 business days of the due date to avoid service interruption.",
    "This agreement is governed by and construed in accordance with applicable financial regulations.",
    "Any disputes arising from this agreement shall be resolved through mutual consultation within 30 days.",
    "This document is system-generated and legally binding once countersigned by both parties."
  ];
  doc.fillColor(COLOR.subtle).font("Helvetica").fontSize(9);
  const xLeft = 40;
  const width = doc.page.width - 80;
  items.forEach((t, i) => {
    doc.text(`${i + 1}. ${t}`, xLeft, doc.y, { width, lineGap: 2 });
    doc.moveDown(0.5);
  });
  doc.moveDown(1);
}

function drawSignatures(doc, meta) {
  doc.addPage();
  const xLeft = 40;
  const xRight = doc.page.width - 40;
  const colW = (xRight - xLeft - 40) / 2;
  const topY = 90;

  doc.save();
  doc.strokeColor(COLOR.border).lineWidth(0.5).moveTo(xLeft, topY - 18).lineTo(xRight, topY - 18).stroke();
  doc.restore();

  doc.fillColor(COLOR.text).font("Helvetica-Bold").fontSize(10);
  doc.text("CLIENT SIGNATURE", xLeft, topY, { characterSpacing: 0.5 });
  doc.text("SERVICE PROVIDER", xLeft + colW + 40, topY, { characterSpacing: 0.5 });

  const lineY = topY + 44;
  doc.save();
  doc.strokeColor(COLOR.text).lineWidth(0.8);
  doc.moveTo(xLeft, lineY).lineTo(xLeft + colW - 40, lineY).stroke();
  doc.moveTo(xLeft + colW + 40, lineY).lineTo(xLeft + 2 * colW, lineY).stroke();
  doc.restore();

  doc.fillColor(COLOR.subtle).font("Helvetica").fontSize(9);
  doc.text("Authorised Signatory / Client", xLeft, lineY + 8);
  doc.text("Date: _______________",       xLeft, lineY + 22);

  doc.text(PLATFORM_NAME,                  xLeft + colW + 40, lineY + 8);
  doc.text(`Date: ${formatLongDate(meta.generatedAt)}`, xLeft + colW + 40, lineY + 22);
}

function buildCompanyName(user) {
  if (!user) return "Client";
  const raw = (user.name || "").trim();
  if (!raw) return user.email || "Client";
  if (/company|ltd|llp|inc\.?|pvt|enterprise|corp/i.test(raw)) return raw;
  const first = raw.split(/\s+/)[0];
  return `${first}'s company`;
}

function streamStatementPdf(res, { user, expenses }) {
  const generatedAt = new Date();
  const meta = {
    companyName: buildCompanyName(user),
    agreementNo: agreementId(generatedAt),
    generatedAt,
    period: periodLabel(generatedAt),
    status: "ACTIVE"
  };

  const filename = `SLA-ExpenseOrbit-${formatISODate(generatedAt).replace(/-/g, "")}.pdf`;
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);

  const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
  doc.pipe(res);

  let drawingFooters = false;
  doc.on("pageAdded", () => {
    if (drawingFooters) return;
    drawTopBar(doc);
    doc.y = 54;
  });

  drawTopBar(doc);
  doc.y = 54;
  drawHeader(doc, meta);

  const summary = summarize(expenses);
  drawKpis(doc, summary);

  drawSectionTitle(doc, "SCHEDULE A — EXPENSE LEDGER");
  drawLedgerTable(doc, expenses, summary);

  drawTerms(doc);

  drawSignatures(doc, meta);

  drawingFooters = true;
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    drawFooter(doc, meta, i + 1, range.count);
  }

  doc.end();
}

module.exports = { streamStatementPdf };
